export class ManageBorrowers {
    keyId!:number;
        loan!:number;
        loanAmt!:string;
        investAmt!:number;
        isGroup!:boolean;
        risk!:string;
        age!:string;
        cibil!:number;
        lScore!:string;
        interest!:string;
        tenureType!:string;
        tenure!:number;
        isEligible!:boolean;
        isLive!:string;
        isRepeat!:false;
        loanCount!:number;
        leftAmt!:string;
        status!:number;
        statusMsg!:string;
        createdDate!:Date;
}
