export class P2PModel 
{
     settingsId!:number;
     isEnabled!:boolean;
     limitPerDay!:number;
     tPin!:string;
     investAmt!:number;
     minInvestAmt!:number;   
     investAmtA!:number;
     investAmtB!:number;
     investAmtC!:number;
     investAmtD!:number; 
     investAmtE!:number; 
     investAmtX!:number;
     cibilPoor!:number;
     cibilAverage!:number;
     cibilGood!:number;
     cibilExcellent!:number;
     smtpFromUser!:string;
     smtpFromEmailAddress!:string;
     smtpHost!:string;
     smtpPort!:number;
     smtpUserName!:string;
     smtpPassword!:string;
     createdOn!:Date;
     modifiedDate!:Date;
     isGroupEnabled!:boolean;
     amountPerBorrowerGroup!:string;
     gCibilGood!:string;
     cibilBest!:string;
     investmentLimit!:number;
     escroBalance!:number;
     balanceThreshold!:number;
     groupLoanI2IFundingEnabled!:boolean;
     memberLoanI2IFundingEnabled!:boolean;	
     memberLoanLendenClubEnabled!:boolean;	
     withdrawaI2IFundingEnabled!:boolean;	
     withdrawaLendenClubEnabled!:boolean;	
     i2IWithdrawAmt!:number;	
     lcWithdrawAmt!:number;	
     lendenEscroBalance!:number;
     i2IPrincipalBalance!:number;
     i2ITotalInvested!:number;
     i2ITotalWithdrawn!:number;
     i2IMyInvestmentBalance!:number;
     i2IDiffAmount!:number;
}



